import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the interface for the authentication state
export interface AuthState {
    token: string | null;
}

// Define the initial state for the authentication slice
const initialState: AuthState = {
    token: null,
}

// Create the authentication slice
const authSlice = createSlice({
    name: 'auth',
    initialState: initialState,
    reducers: {
        // Define the setToken reducer
        setToken: (state, action: PayloadAction<string>) => {
            state.token = action.payload;
        },
        // Define the clearToken reducer
        clearToken: (state) => {
            state.token = null;
        },
    }
})

// Export the action creators generated by createSlice
export const { setToken, clearToken } = authSlice.actions;

// Export the reducer function generated by createSlice
export default authSlice.reducer;
